server:
  port: $PORT

spring:
  datasource:
    url: ${ CLEARDB_DATABASE_URL }
    username: ${ CLEARDB_DATABASE_USERNAME }
    password: ${ CLEARDB_DATABASE_PASSWORD }
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
cloud:
  aws:
    credentials:
      accessKey: ${ APPLICATION_ACCESSKEY }
      secretKey: ${ APPLICATION_SECRETKEY }
    s3:
      bucket: ${ APPLICATION_BUCKET }
    region:
      static: ap-northeast-2
jwt:
  secret: ${ APPLICATION_JWT }