name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
  
      - name: Generate env
        run:
          echo "APPLICAION_DB_URL=$APPLICAION_DB_URL" >> env.properties
          echo "APPLICAION_DB_USERNAME=$APPLICAION_DB_USERNAME" >> env.properties
          echo "APPLICAION_DB_PASSWORD=$APPLICAION_DB_PASSWORD" >> env.properties
          echo "APPLICATION_ACCESSKEY=$APPLICATION_ACCESSKEY" >> env.properties
          echo "APPLICATION_SECRETKEY=$APPLICATION_SECRETKEY" >> env.properties
          echo "APPLICATION_BUCKET=$APPLICATION_BUCKET" >> env.properties
          echo "APPLICATION_JWT=$APPLICATION_JWT" >> env.properties
        env:
          APPLICAION_DB_URL: ${{ secrets.APPLICATION_DB_URL }}
          APPLICATION_DB_USERNAME: ${{ secrets.APPLICATION_DB_USERNAME }}
          APPLICATION_DB_PASSWORD: ${{ secrets.APPLICATION_DB_PASSWORD }}
          APPLICATION_ACCESSKEY: ${{ secrets.APPLICATION_ACCESSKEY }}
          APPLICATION_SECRETKEY: ${{ secrets.APPLICATION_SECRETKEY }}
          APPLICATION_BUCKET: ${{ secrets.APPLICATION_BUCKET }}
          APPLICATION_JWT: ${{ secrets.APPLICATION_JWT }}
      
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: clone-airbnb-t2
          heroku_email: ${{secrets.HEROKU_EMAIL}}
